version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped